telegram:
  bot:
    webhook:  https://7723-89-106-170-30.eu.ngrok.io
    name: "@L1zk1nBot"
    token: 5711225760:AAHLiLUGOs3Rmfow69xlbFq77oBOx6gBxsQ
spring:
  #локал
    datasource:
      hikari:
        username: java
        password: pass
        jdbc-url: jdbc:postgresql://localhost:5432/yo
      url: jdbc:postgresql://localhost:5432/yo

  # для hikari
    jpa:
      show-sql: true
#  datasource:
#    hikari:
#      username: nlynipmseatzsm
#      password: fed3d46587fb2a0f865a3a1f3ca26ee8e9976e25aa28c3c46ffca55202d6ba2a
#    #      jdbc-url: postgres://nlynipmseatzsm:fed3d46587fb2a0f865a3a1f3ca26ee8e9976e25aa28c3c46ffca55202d6ba2a@ec2-34-249-161-200.eu-west-1.compute.amazonaws.com:5432/d9cioqhsevoagg
#    url: postgres://nlynipmseatzsm:fed3d46587fb2a0f865a3a1f3ca26ee8e9976e25aa28c3c46ffca55202d6ba2a@ec2-34-249-161-200.eu-west-1.compute.amazonaws.com:5432/d9cioqhsevoagg

#  https://api.telegram.org/bot5711225760:AAHLiLUGOs3Rmfow69xlbFq77oBOx6gBxsQ/setWebhook?url=<URL, полученный от ngrok>